routes/web.php
<?php

use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/tasks', TaskController::class)->except('index');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Task Model
 */
class Task extends Model
{
    protected $guarded = [
        '_method',
        '_token'
    ];

    use HasFactory;

    /**
     * get the user who owns the task
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * User Model
 */
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

    /**
     * Get user tasks
     */
    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $tasksQuery = Task::query();

        if ($request->has('sort_asc')) {
            $tasksQuery->orderBy('created_at');
        }

        if ($request->has('sort_desc')) {
            $tasksQuery->orderByDesc('created_at');
        }

        if ($request->has('state')) {
            if ($request['state'] == 0) {
                $tasksQuery->where('status', '=', '0');
            } elseif ($request['state'] == 1) {
                $tasksQuery->where('status', '=', '1');
            }
        }

        $tasks = $tasksQuery
            ->where('user_id', '=', Auth::user()->id)
            ->paginate(3)
            ->withPath("?" . $request->getQueryString());

        return view('home', compact('tasks'));
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/**
 * Controller for processing task
 */
class TaskController extends Controller
{
    /**
     * Return form for creating task
     */
    public function create()
    {
        return view('tasks.create');
    }

    /**
     * Create task action
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:255|min:10',
            'description' => 'required|min:10',
        ]);

        $params = $request->all();
        $params['user_id'] = Auth::user()->id;
        Task::create($params);
        return redirect()->route('home')->withSuccess('Created task: ' . $request->title);
    }

    /**
     * Return detailed view of task
     */
    public function show(Task $task)
    {
        $this->authorize('view', $task);

        return view('tasks.show', compact('task'));
    }

    /**
     * Return form for editing task
     */
    public function edit(Task $task)
    {
        $this->authorize('update', $task);

        return view('tasks.edit', compact('task'));
    }

    /**
     * Update task action
     */
    public function update(Request $request, Task $task)
    {
        $request->validate([
            'title' => 'required|max:255|min:10',
            'description' => 'required|min:10',
        ]);

        $this->authorize('update', $task);

        if (!$request->has('status')) {
            $request['status'] = 0;
        }

        $task->update($request->all());
        return redirect()->route('home')->withSuccess('Updated task: ' . $task->title);
    }

    /**
     * Delete task action
     */
    public function destroy(Task $task)
    {
        $this->authorize('delete', $task);

        $task->delete();

        return redirect()->route('home')->withSuccess('Deleted task: ' . $task->title);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card mt-3">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    <form method="GET" action="{{ route('home') }}" class="mt-3">
                        <div class="filters row">
                            <div class="col-sm-6 col-md-3">
                                <p>Сортировать по дате:</p>
                                <label for="sort_asc">Сначала старые
                                    <input type="checkbox" name="sort_asc" id="sort_asc" size="6" value="{{ request()->sort_asc }}">
                                </label>
                                <label for="sort_desc">Сначала новые
                                    <input type="checkbox" name="sort_desc" id="sort_desc" size="6"  value="{{ request()->sort_desc }}">
                                </label>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <p>Фильтровать по статусу:</p>
                                <label for="filter_opened">Только открытые задачи
                                    <input type="radio" name="state" id="filter_opened" size="6"  value="0">
                                </label>
                                <label for="filter_closed">Только закрытые задачи
                                    <input type="radio" name="state" id="filter_closed" size="6"  value="1">
                                </label>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <button type="submit" class="btn btn-primary">Применить</button>
                                <a href="{{ route('home') }}" class="btn btn-warning">Сброс</a>
                            </div>
                        </div>
                    </form>
                    <a type="button" class="btn btn-secondary mt-3" href="{{ route('tasks.create') }}"
                       xmlns="http://www.w3.org/1999/html">Create task</a>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table class="table table-bordered mt-3">
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Created at</th>
                            <th>Actions</th>
                        </tr>
                        @foreach ($tasks as $task)
                            <tr>
                                <td>{{ $task->title }}</td>
                                <td>{{ $task->description }}</td>
                                <td>{{ $task->created_at }}</td>
                                <td class="input-group">
                                    <a class="btn btn-info" href="{{ route('tasks.show', $task->id) }}">Show</a>
                                    <a class="btn btn-primary" href="{{ route('tasks.edit', $task->id) }}">Edit</a>
                                    <form action="{{ route('tasks.destroy', $task->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </table>
                    <div class="mt-3">{{ $tasks->links() }}</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="container">
            @if(session()->has('success'))
                <p class="alert alert-success mt-3">{{ session()->get('success') }}</p>
            @endif
            @if(session()->has('warning'))
                <p class="alert alert-warning mt-3">{{ session()->get('warning') }}</p>
            @endif
            @yield('content')
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script></body>
</html>

resources/views/tasks/create.blade.php
@extends('layouts.app')
@section('content')
    <a type="button" class="btn btn-secondary mt-3" href="{{ route('home') }}"
       xmlns="http://www.w3.org/1999/html">Back home</a>
    <form action="{{ route('tasks.store') }}" method="POST">
        @csrf
        <div class="input-group row mt-3">
            <label for="title" class="col-sm-2 col-form-label">Title:</label>
            <div class="col-sm-6">
                <input name="title" type="text" class="form-control" placeholder="title" aria-label="title" value="{{ old('title') }}">
                @error('title')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>

        <div class="input-group row mt-3">
            <label for="description" class="col-sm-2 col-form-label">Description:</label>
            <div class="col-sm-6">
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description">
                    {{ old('description') }}
                </textarea>
                @error('description')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <button type="submit" class="btn btn-success">Create</button>
            </div>
        </div>
    </form>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')
@section('content')
    <a type="button" class="btn btn-secondary mt-3" href="{{ route('home') }}"
       xmlns="http://www.w3.org/1999/html">Back home</a>
    <form action="{{ route('tasks.update', $task->id) }}" method="POST">
        @csrf

        @method('PUT')
        <div class="input-group row mt-3">
            <label for="title" class="col-sm-2 col-form-label">Title:</label>
            <div class="col-sm-6">
                <input name="title" type="text" class="form-control" placeholder="title" aria-label="title"
                       value="{{ old('title', $task->title) }}">
                @error('title')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>

        <div class="input-group row mt-3">
            <label for="description" class="col-sm-2 col-form-label">Description:</label>
            <div class="col-sm-6">
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description">
                    @isset($task){{ old('description', $task->description) }}@endisset
                </textarea>
                @error('description')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>

        <div class="input-group row mt-3">
            <label for="status" class="col-sm-2 col-form-label">Status:</label>
            <div class="col-sm-6">
                <input id="status" name="status" type="checkbox" placeholder="status" aria-label="status" value="1"
                       @if($task->status) checked @endif>
                @error('status')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>
    </form>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')
@section('content')

    <div class="input-group row mt-3">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Show task №{{ $task->id }}</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('home') }}">Back</a>
            </div>
        </div>
    </div>

    <div class="input-group row mt-3">
        <div class="col-sm-6">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $task->title }}
            </div>
        </div>
    </div>
    <div class="input-group row mt-3">
        <div class="col-sm-6">
            <div class="form-group">
                <strong>Description:</strong>
                {{ $task->description }}
            </div>
        </div>
    </div>
    <div class="input-group row mt-3">
        <div class="col-sm-6">
            <div class="form-group">
                <strong>Time of creation:</strong>
                {{ $task->created_at }}
            </div>
        </div>
    </div>
    <div class="input-group row mt-3">
        <div class="col-sm-6">
            <div class="form-group">
                <strong>Status:</strong>
                @if($task->status == 0)
                    In Progress
                @else
                    Closed
                @endif
            </div>
        </div>
    </div>
@endsection